apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.backend.appName }}-configmap
data:
  db_host: "{{ .Values.backend.config.db_host }}"
  db_user: "{{ .Values.backend.config.db_user }}"
  db_password: "{{ .Values.backend.config.db_password }}"
  db_name: "{{ .Values.backend.config.db_name }}"
  db_port: "{{ .Values.backend.config.db_port }}"