apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.database.appName }}-service
spec:
  selector:
    app: {{ .Values.database.appName }}
  ports:
    - protocol: TCP
      port: {{ .Values.database.containerPort }}
      targetPort: {{ .Values.database.containerPort }}