apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.backend.appName }}-httproute
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: http-gateway  # Nom de la gateway globale fourni dans le cours
      namespace: nginx-gateway
  hostnames:
    - {{ .Values.backend.host }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .Values.backend.appName }}-service
          port: {{ .Values.backend.servicePort }}