name: On code change
on:
    pull_request:
        types: [opened, reopened, synchronize]

jobs:
    static-analysis:
        name: Static analysis
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-python@v4
            - uses: actions/checkout@v4
            - name: Setup environment
              shell: bash
              run: pip install -r requirements/dev.txt
            - name: Run lint
              shell: bash
              run: ruff format --check