on:
    push:
        branches: main

        
jobs:
    static-analysis:
        name: Static analysis
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-python@v4
            - uses: actions/checkout@v4
            - name: Setup environment
              shell: bash
              run: pip install -r requirements/dev.txt
            - name: Run lint
              shell: bash
              run: ruff format --check
    unit-test:
        needs: static-analysis
        name: Unit tests
        runs-on: ubuntu-latest
        services:
          db:
            image: postgres:17.2
            env: 
              POSTGRES_DB: ${{ secrets.POSTGRES_DB}}
              POSTGRES_USER: ${{ secrets.POSTGRES_USER}}
              POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
            ports:
              - "5432:5432"
            volumes:
              - db_data:/var/lib/postgresql/data
        steps:
          - uses: actions/setup-python@v4
          - uses: actions/checkout@v4
          - name: Setup environment
            shell: bash
            run: pip install -r requirements/dev.txt
          - name: Run lint
            shell: bash
            run: python manage.py test
    build:
        needs: unit-test
        name: Build the project
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Login to docker
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build the docker image
              uses: docker/build-push-action@v2
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/devops_back:latest
    helm-deploy:
      needs: build
      name: Helm Deploy
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        # Installation de Helm
        - name: Install Helm
          uses: azure/setup-helm@v4

        - name: Configure Kubeconfig
          uses: azure/k8s-set-context@v4
          with:
            method: kubeconfig
            kubeconfig: ${{ secrets.KUBECONFIG }}

        # Déploiement via Helm (assurez-vous que votre chart se trouve dans le dossier "helm-chart")
        - name: Deploy Front using Helm
          run: |
            helm upgrade --install backend-chart ./backend-chart \
              --namespace baguette-groupe-3
    healthcheck:
      needs: helm-deploy
      name: Health Check
      runs-on: ubuntu-latest
      steps:
        - name: Check Health Endpoint
          run: |
            for i in {1..10}; do
              response=$(curl --silent --fail https://backend-baguette.jbienvenu.fr/health/ || true)
              if echo "$response" | grep -q '"status": *"OK"'; then
                echo "Health check passed!"
                exit 0
              fi
              echo "Health check failed, retrying in 10 seconds..."
              sleep 10
            done
            echo "Health check did not pass."
            exit 1
